services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: spring_app
    restart: on-failure
    ports:
      - "${BE_PORT}:${BE_PORT}"
    environment:
      - PORT=${BE_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=${DB_DRIVER}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    container_name: react_app
    restart: on-failure
    ports:
      - "${FE_PORT}:80"
    depends_on:
      - backend